### ISSUE TITLE
Make Tree Drop from Explorer recursive

### ISSUE THREAD

**Issue by Jooshua** [Jooshua/e4CompareFramework-team2#21]
- [x] If a directory is dropped open a Wizard that asks if the user wants to copy all nested files/dirs.
- [x] Also add choice of shallow (first level children) or full recursive

**Comment by valentinpurrucker** [comment]
this wizard uses a fxml file to load in the layout. Maybe i should make an abstract wizard so all future wizards have a similiar structure. Right now the wizard only appears when dropping elements from the system's explorer, i should probably also add this behavior when doing in-view drag-and-drop. The way the wizard gets called right now is a bit hacky, but hey... it works :D

**Comment by timbittner** [comment]
Wizard Abstraction is something to be considered in #25 by @kyshidar.
Providing a sensible representation should be enough on your end.

Regarding that weirdness: I think you reference the event posts from the tree cell? I find that perfectly acceptable as you need the shell and the best place will be in view controller.

Before attempting to address in-tree DND stuff we should merge #28 as it rewrites part of that :)

**Comment by Jooshua** [comment]
Nice one, some minor things to consider here:
- If we drop an empty directory we don't need the wizard
- Currently the wizard gets called and then the whole loop get's exited (`return`). I find the following behavior more user friendly: On the first not empty directory we call the wizard once and apply the chosen setting for all currently dropped directories

**Comment by valentinpurrucker** [comment]
- The misbehavior is now fixed, so if you drop an empty directory you don't get the wizard, which makes sense :D
- in order to apply the copying behavior to all directories with content in it, the DropElement now supports not a single but multiple source paths, that makes copying multiple directories easy.

**Comment by valentinpurrucker** [comment]
In latest commit i forgot adding the task id, so here's what i did.
- Replacing the functional interfaces with lambdas in the WizardPages
- fixed the missing page titles

**Comment by Jooshua** [comment]
Closed via https://github.com/TUBS-ISF/e4CompareFramework/pull/10
