### ISSUE TITLE
Add flat view of directory structure

### ISSUE THREAD

**Issue by Jooshua** [Jooshua/e4CompareFramework-team2#23]
A list instead of a tree, with button in toolbar to toggle behavior.

**Comment by Jooshua** [comment]
Some design decision here is if there should be drag and drop in the flat view?
I think we could do it, because we have the FileTreeElements in the background, so the question probably has to be answered from a usability point of view.

**Comment by Jooshua** [comment]
Added functionality to build the flat tree. This only has to be connected to a toolbar (see #22 and #26), to switch between the views.

**Comment by timbittner** [comment]
We should consider saving the expansion state of nodes in a field in contrast to rebuilding it everytime we refresh. This would lead to more consistent user experience when switchting between flat/hier view and searches.

**Comment by Jooshua** [comment]
Closed via https://github.com/TUBS-ISF/e4CompareFramework/pull/10
