### ISSUE TITLE
Inline Renaming

### ISSUE THREAD

**Issue by Jooshua** [Jooshua/e4CompareFramework-team2#24]
Leveraging the tree cell without the wizard.
Remove rename wizard from context menu.

**Comment by valentinpurrucker** [comment]
Rename functionality is same as in the previous non-JavaFx Version, so it is only possible to change the name of empty directories.
We need to discuss additional functionality.

**Comment by Jooshua** [comment]
Still good job! I tested it and you can also rename a folder that only contains files.

**Comment by timbittner** [comment]
I played around a little and my current hypothesis is, that the rename handling in and of itself is fine.
It does work as expected when watching the Windows FileSystem while editing in the ProjectExplorer.

I would suggest looking into the refresh functionality.

**Comment by timbittner** [comment]
Created a new branch from team-02-dev for this feature and resolved the merge issues between feature/task_24-inline_renaming

Also started on recursive actions but they create hard to debug async file-system-synchronization errors.
(Other than printing error messages they seem to work however...)

**Comment by Jooshua** [comment]
> 
> 
> Created a new branch from team-02-dev for this feature and resolved the merge issues between feature/task_24-inline_renaming
> 
> Also started on recursive actions but they create hard to debug async file-system-synchronization errors.
> (Other than printing error messages they seem to work however...)

⚠️WIP: Doesn't work as expected yet!!!

**Comment by timbittner** [comment]
> > Created a new branch from team-02-dev for this feature and resolved the merge issues between feature/task_24-inline_renaming
> > Also started on recursive actions but they create hard to debug async file-system-synchronization errors.
> > (Other than printing error messages they seem to work however...)
> 
> ⚠️WIP: Doesn't work as expected yet!!!

I can not reproduce any issues. Can you please tell me how to reproduce them?

**Comment by Jooshua** [comment]
> 
> 
> > > Created a new branch from team-02-dev for this feature and resolved the merge issues between feature/task_24-inline_renaming
> > > Also started on recursive actions but they create hard to debug async file-system-synchronization errors.
> > > (Other than printing error messages they seem to work however...)
> > 
> > 
> > ⚠️WIP: Doesn't work as expected yet!!!
> 
> I can not reproduce any issues. Can you please tell me how to reproduce them?

As it seems you are right and I have to commit seppuku now. C u at the other side tho

**Comment by valipu** [comment]
As far as i understand the current version throws Null-Pointer-Exceptions when doing renaming even on empty directories. However, this can be fixed by changing the check if a given FileElement is a project to 
if (fileElement.getParent() == null) {
				return null;
}. This also fixes the Bug where different icons are shown for 1st or nth level directories. I hope i'm not the only one experiencing these issues.

**Comment by Jooshua** [comment]
Closed via #30
