### ISSUE TITLE
Wizard migration

### ISSUE THREAD

**Issue by Jooshua** [Jooshua/e4CompareFramework-team2#25]
- [x] Check project for existing abstract wizards
  - [x] Add abstract wizard widget
    - [x] Wizard FX-Migration

**Comment by timbittner** [comment]
Import .... Wizard should be replaced by FileChooser
That Chooser can select multiple files and directories.
If directories are contained in selection, then the RecursiveDrop Wizard should be Utilized from #21

**Comment by Jooshua** [comment]
Closed via https://github.com/TUBS-ISF/e4CompareFramework/pull/10
