### ISSUE TITLE
Toolbar Icons & Mnemonics

### ISSUE THREAD

**Issue by Jooshua** [Jooshua/e4CompareFramework-team2#26]
Add Icons to the toolbar & Mnemonics for Create Folder, Create File, …

**Comment by timbittner** [comment]
Dynamically filling the Toolbar (and FX Context Menus #7)  might be possible by accessing the project explorer parts' MMenus.
A starting point might be provided by the following code snippet, given that the required packages are added to the project's dependencies:

```
// get the swt popup menu
PartImpl projExPart = (PartImpl) services.partService.partService.findPart("de.tu_bs.cs.isf.e4cf.parts.project_explorer");
PopupMenuImpl swtMenu = null;
for ( MMenu eo : projExPart.getMenus()) {
	if (eo instanceof PopupMenuImpl) {
		swtMenu = (PopupMenuImpl)eo;
		break;
	}
}

// Add icons for all menu entries
for ( MMenuElement menuItem : swtMenu.getChildren()) {
	
	System.out.println("  Popup Menu Entries: " + menuItem.getLabel());
	
}
```

This however requires emulating some parts of the e4 framework (loading bundleclasses, invoking handlers...) and is therefore an additional task that requires much more work than this issue.

The benefits of such an approach would be the ability to use the e4xmi files across the framework to enhance the toolbar just like swt context menus.

**Comment by timbittner** [comment]
Ready to be merged, after mutliselection https://github.com/Jooshua/e4CompareFramework-team2/pull/32 was integrated and tested with toolbar as well.

**Comment by Jooshua** [comment]
Closed via https://github.com/TUBS-ISF/e4CompareFramework/pull/10
