### ISSUE TITLE
Two different icons for directories

### ISSUE THREAD

**Issue by Jooshua** [Jooshua/e4CompareFramework-team2#27]
It seems the root folders have a different icon than the other folders. This probably is a bug  and has to be investigated. Or at least we should change the images.
![grafik](https://user-images.githubusercontent.com/26773525/100619909-10462500-331e-11eb-806c-6885a6f60593.png)

**Comment by timbittner** [comment]
This is a feature and it's working as intended, because root folders are considered "projects".

**Comment by Jooshua** [comment]
Ok then let's at least change one of the icons

**Comment by Jooshua** [comment]
Closed via https://github.com/TUBS-ISF/e4CompareFramework/pull/10
