### ISSUE TITLE
Improve file synchronization

### ISSUE THREAD

**Issue by Jooshua** [Jooshua/e4CompareFramework-team2#44]
Investigate and see what can be done

**Comment by timbittner** [comment]
There are already TODOs in code that reference enhancing the file system so I would suggest not interfering with this in the context of this project.

Extracted from `de.tu_bs.cs.isf.e4cf.core.file_structure.WorkspaceFileSystem`:
`// TODO: Create ExtensionManager that is extendible by plugins`
`// --> holds a map for load/save operations`
`// --> holds a map for icons association`

**Comment by Jooshua** [comment]
Nothing to do for us here
