### ISSUE TITLE
Tagging add editing

### ISSUE THREAD

**Issue by Jooshua** [Jooshua/e4CompareFramework-team2#49]
via context menu with dialogs

**Comment by valentinpurrucker** [comment]
- TODO: Add Tag icon for context menu
- look into problem with tagservice - currently the actual tags DO NOT work; just the front-end side works

Done:
- layout via fxml
- user can add tags to file(s) -> also multiple files altough the behavior is the same as it is on MacOS -> if multiple files are selected and there are files that have more tags than the rest, the union of all tags are applied to the files.
- applying tags is done via selecting the tags in a listview -> simple selection as it is in explorer view -> no need for checkboxes

**Comment by Jooshua** [comment]
I will also look into the backend problem. I really like the edit available tags view. But the selection feels not so good for me, maybe we could try something more like this, with these kind of checking directly in the menu without a dialog:
![grafik](https://user-images.githubusercontent.com/26773525/104763263-e463ef00-5765-11eb-809b-478c620ebdb1.png)

**Comment by valentinpurrucker** [comment]
Changes:
- tags on one single page
- update available through double click
- select tags via chechboxes
- some code cleanup

**Comment by Jooshua** [comment]
Closed https://github.com/TUBS-ISF/e4CompareFramework/pull/13
